config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  root to: 'pages#homepage'

  devise_for :users
  get '/pages', to: 'pages#dashboard', as: :dashboard
  get '/pages/my_bookings', to: 'pages#my_bookings', as: :my_bookings
  get '/pages/my_activities', to: 'pages#my_activities', as: :my_activities
  resources :activities, only: [:index, :new, :show, :create, :edit, :update, :destroy] do

    resources :bookings, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  end
  resources :bookings, only: [:index] do
    member do
      patch :accept
      patch :decline
    end

  end
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :title, :description, :price, :level, :location, :group_size, presence: true

  validates :price, numericality: { only_float: true }
  validates :group_size, numericality: { only_integer: true }
  validates :level, inclusion: { in: ['Beginner', 'Intermediate', 'Advance'] }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :activity
  belongs_to :user

  validates :start_time, :end_time, :status, :spots_required, presence: true
  validates :spots_required, numericality: { only_integer: true }
  validates :status, inclusion: { in: ['Not confirmed', 'Confirmed'] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :activities
  has_many :bookings
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = policy_scope(Activity)
  end

  def new
    @activity = Activity.new
    authorize @activity
  end

  def show
    @activity = Activity.find(params[:id])
    authorize @activity
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    authorize @activity
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
    authorize @activity
  end

  def update
    @activity = Activity.find(params[:id])
    # @activity.user = current_user
    @activity.update(activity_params)
    authorize @activity
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    authorize @activity
    redirect_to activities_path
  end

  private

  def activity_params
    params.require(:activity).permit(:title, :description, :level, :location, :price, :group_size, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :set_query

  def set_query
    @query = Activity.ransack(params[:id])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
    @activity = Activity.find(params[:activity_id])
  end

  def new
    @activity = Activity.find(params[:activity_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @activity = Activity.find(params[:activity_id])
    authorize @booking
    @booking.activity = @activity
    @booking.user = current_user
    @booking.status = "Not confirmed"
    if @booking.save
      redirect_to activity_booking_path(@activity, @booking)
    else
      render :new
    end
  end


  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end


  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "Confirmed"
    @booking.save
    redirect_to activity_booking_path([@booking.activity, @booking])
    skip_policy_scope
    skip_authorization
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "Not confirmed"
    @booking.save
    redirect_to activity_booking_path([@booking.activity, @booking])
    skip_policy_scope
    skip_authorization
  end


  def edit
    @booking = Booking.find(params[:id])
    @activity = @booking.activity
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to activity_booking_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to activities_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :status, :spots_required, :user_id, :activity_id, :booking_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:homepage, :my_bookings, :my_activities]

  def dashboard
  end

  def homepage
  end

  def my_bookings
    @user = current_user
    @bookings = Booking.where(user_id: current_user.id)
    # @activity = @bookings.activity_id
  end

  def my_activities
    @activities = Activity.where(user_id: current_user.id)
    # @bookings = Booking.where(activity: @activity)
  end

  # def landing
  # end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Activity.ransack(params[:q])
    @activities = @query.result(distinct: true)
    @users = User.all
    skip_policy_scope
    skip_authorization
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<div class="main-container">
  <div id="activities" class="flex-item-1">
    <h1>PLAY BY YOUR RULES</h1>
  </div>
    <div class="flex-item-2">
      <div class="details-form pd-2 mb-4">
        <%= simple_form_for(@activity) do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :level, :collection => %w[Beginner Intermediate Advance]%>
          <%= f.input :location %>
          <%= f.input :price, input_html: { min: '0', step: '1' }%>
          <%= f.input :group_size, input_html: { min: '1', max: '25' }%>
          <%= f.submit "Create Activity", class: "btn btn-primary" %>
          <%= f.button :button do %>
          <button type="button" class="btn btn-outline-primary"><%= link_to "Back to Activities", activities_path %></button>
        <% end %>
        <% end %>
      </div>
    </div>
</div>

app/views/activities/edit.html.erb
<div class="main-container">
  <div id="activities" class="flex-item-1">
    <h1>THAT'S A GAME CHANGER</h1>
  </div>
    <div class="flex-item-2">
        <%= simple_form_for @activity do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :level, :collection => %w[Beginner Intermediate Advance]%>
          <%= f.input :location %>
          <%= f.input :price, input_html: { min: '0', step: '1' } %>
          <%= f.input :group_size, input_html: { min: '1', max: '25' }%>
          <%= f.submit "Save", class:"btn btn-primary" %>
          <%= f.button :button do %>
            <button type="button" class="btn btn-outline-primary"><%= link_to "Back to Activities", activities_path %></button>
        <% end %>
      <% end %>
  </div>
</div>

app/views/activities/index.html.erb
<h1 class="text-center m-20" style="margin-bottom: 20px;"></h1>

<div class="activities-index-container">
  <div class="row justify-content-center">
  <div class="text-center m-20 col-12 " style="background-color:#E5E5E5;height: 250px;margin-bottom: 20px; padding:50px">
     <div>
      <h1 ><strong>THE BALL IS IN YOUR COURT</strong></h1>
      <p>Your are an expert in a sport and would like to teach the community?
      <br> Don't sweat it, you can share your talent with the community now!</p>
     </div>
     <div>
      <button type="button" class= "btn btn-primary pt-10" ><%= link_to "Create a new activity", new_activity_path %></button>
      </div>
    </div>
  </div>
</div>

<div class="card-container">
  <div class="cards col-sm-6 col-lg-10">
    <% @activities.each do |activity| %>
      <div class="card-product" style="display: flex;flex-direction: column;justify-content: space-evenly;">

        <div><img src="https://source.unsplash.com/random/?<%= activity.title %>"/>
        </div>

        <div style ="text-decoration:none;">
        <p style="margin-top: 20px">
          <strong style="text-transform: uppercase;"><%= activity.title.capitalize() %></strong>
            <br>
            <%= activity.location %>
            <br>
            $<%= activity.price%>/hr
            <br>
            <%= link_to "More info", activity_path(activity), class:"btn btn-outline-primary", style:"margin-top: 15px" %>
            </p>
          </div>

      </div>
      <% end %>
  </div>
</div>

<div class="footer">
  <div class="footer-logo">
    <%= image_tag "sportsmate.png", alt: "Sportsmate-white", width: 161 %>
  </div>
  <div class="footer-team">
    <ul class="no-bullets">
    <li><h2>TEAM BORRO</h2></li>
      <li><p>Anuth Hatharasinghe</p></li>
      <li><p>Chichi</p></li>
      <li><p>Francesca Mo</p></li>
      <li><p>Chloe Chemin</p></li>
    </ul>
  </div>
</div>

app/views/activities/new.html.erb
<%= render "form", activity: @activity %>

app/views/activities/show.html.erb
<div id="container-activity-page">
  <div class="flex-container-activity">
    <div class="flex-item-activity">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/random/?<%=@activity.title %>)">
      </div>
    </div>
    <div class="flex-item-activity">
      <div class="activity-show-container">
        <div class="row justify-content-center align-center">
          <div class="content_activity">
            <div class="col-18 m-2 p-2">
              <div class="title">
                <h1><%=@activity.title.upcase %></h1>
                <a class="username_link" href="">by <%=@activity.user.username.capitalize %></a>
              </div>
              <div class= "descrition pt-3">
                <p><%=  @activity.description %></p>
              </div>
                <div class= "details pt-3">
                  <div class= "d-flex pb-1">
                    <%= image_tag "icons/level_icon.png", width: "40px", height: "40px", alt: "Level", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1"> <%= @activity.level %></p>
                  </div>
                  <div class= "d-flex pb-1">
                    <%= image_tag "icons/people_icon.png", width: "40px", height: "40px", alt: "People", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1"> up to <%= @activity.group_size %> people</p>
                  </div>
                  <div class= "d-flex pb-1">
                    <%= image_tag "icons/price_icon.png", width: "40px", height: "40px", alt: "Price", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1">$<%= @activity.price %>/per hr</p>
                  </div>
                  <div class= "d-flex pb-1 mb-4">
                    <%= image_tag "icons/location_icon.png", width: "40px", height: "40px", alt: "Location", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1"><%= @activity.location %></p>
                  </div>
                </div>
              <% if policy(@activity).book? %>
                <button type="button" class="btn btn-primary"><%= link_to "Book", new_activity_booking_path(@activity) %></button>
              <% end %>
              <% if policy(@activity).edit? %>
                <button type="button" class="btn btn-outline-primary"><%= link_to "Edit", edit_activity_path(@activity) %></button>
              <% end %>
              <% if policy(@activity).destroy? %>
                <button type="button" class="btn btn-outline-primary"><%=link_to "Delete",
                    activity_path(@activity),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %></button>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<div class="main-container">
  <div id="activities" class="flex-item-1">
    <h1>CLOSE TO THE FINISH LINE</h1>
  </div>
    <div class="flex-item-2">
        <%= simple_form_for [ @activity, @booking ] do |f| %>
        <%= f.input :start_time, :as => :datetime %>
        <%= f.input :end_time, :as => :datetime %>
        <%= f.input :spots_required, input_html: { min: '1', max: @activity.group_size  }%>
        <%= f.submit "Book", class:"btn btn-primary" %>
        <%= f.button :button do %>
          <button type="button"  class="btn btn-outline-primary"><%= link_to "Back to the activity", activity_path(@activity) %></button>
        <% end %>
      <% end %>
    </div>
</div>

app/views/bookings/edit.html.erb
<div class="main-container">
  <div id="activities" class="flex-item-1">
    <h1>THAT'S A GAME CHANGER </h1>
  </div>
    <div class="flex-item-2">
      <%= simple_form_for [ @activity, @booking ] do |f| %>
      <%= f.input :start_time, :as => :datetime %>
      <%= f.input :end_time, :as => :datetime %>
      <%= f.input :spots_required, input_html: { min: '1', max: @activity.group_size }%>
      <%= f.submit "Book", class:"btn btn-primary" %>
      <%= f.button :button do %>
        <button type="button" class="btn btn-outline-primary"><%= link_to "Back to the activity", root_path %></button>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="main-container">
  <div id="my_booking" class="flex-item-1" >
    <h1>SOME YOU WIN, SOME YOU WIN</h1>
  </div>
  <div class="flex-item-2">
    <div class="cards">
          <div style ="text-decoration:none;">
            <p style="margin-top: 20px">
                <% @bookings.each do |booking| %>
                  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/random/?headshot)"
                  width="500">
                  </div>
                   <%= booking.user.username.capitalize() %>
                <p><%= booking.start_time.strftime('%B %e at %l:%M %p') %></p>
                <p><%= booking.spots_required %> People</p>

                 <%= link_to "Accept", accept_booking_path(booking), class: "btn btn-primary", method: "patch" %>
                <%= link_to "Decline", decline_booking_path(booking), class: "btn btn-outline-primary", method: "patch" %>

                <% end %>
            </p>
          </div>
        </div>


    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>

      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render "form", booking: @booking %>

app/views/bookings/show.html.erb
<div class="activity-show-container">
  <div class="flex-container-activity">
      <div class="flex-item-activity">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://source.unsplash.com/random/?<%=@booking.activity.title %>)">
          <p>THANKS FOR YOUR BOOKING</p>
        </div>
        <p>☺️</p>
      </div>
      <div class="flex-item-activity">
        <div class="activity-show-container">
          <div class="row justify-content-center">
            <div class="content_booking">
              <div class="col-18 m-2 p-2">
                <div class="status">
                  <p><%= @booking.status.upcase %> BY <%=@booking.activity.user.username.upcase %></p>
                </div>
                <div class="title">
                  <h1>YOUR <%=@booking.activity.title.upcase %> CLASS</h1>
                  <a class="username_link" href="">with <%=@booking.activity.user.username.capitalize %></a>
                </div>
                <div class= "details pt-4">
                  <div class= "d-flex pb-1">
                    <%= image_tag "icons/price_icon.png", width: "40px", height: "40px", alt: "Price", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1">$<%= @booking.activity.price %>/per hr</p>
                  </div>
                  <div class= "d-flex pb-1">
                    <%= image_tag "icons/location_icon.png", width: "40px", height: "40px", alt: "Location", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1"><%= @booking.activity.location %></p>
                  </div>
                </div>
                <div class= "details pt-3">
                  <div class= "d-flex pb-1">
                    <%= image_tag "icons/calendar_icon.png", width: "40px", height: "40px", alt: "Calendar", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1">From <%= @booking.start_time.to_time.strftime('%B %e at %l:%M %p')%></p>
                  </div>
                  <div class= "d-flex pb-1">
                    <%= image_tag "icons/people_icon.png", width: "40px", height: "40px", alt: "Spots", class: "icon" %>
                    <p class="flex-grow text-left pt-2 mb-1"><%= @booking.spots_required %> people</p>
                  </div>
                </div>
                <br>
                <br>
                  <% if policy(@booking).edit? %>
                    <button type="button" class="btn btn-outline-primary"><%= link_to "Edit", edit_activity_booking_path(@booking) %></button>
                  <% end %>
                  <% if policy(@booking).destroy? %>
                    <button type="button" class="btn btn-outline-primary"><%=link_to "Cancel",
                        activity_booking_path(@booking),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %></button>
                  <% end %>

              </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SPORTSMATE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <% unless action_name == "homepage" %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="main-container">
  <div class="d-flex flex-column">
      <div class="d-flex flex-row justify-content-around">
        <div class= "menu-card-grey">
          <p><%= link_to "MY ACTIVITIES", my_activities_path %></p>  <%# something /activities %>
        </div>
        <div class= "menu-card-white">
          <p><%= link_to "MY BOOKINGS", my_bookings_path  %></p>  <%# something /bookings %>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-around">
        <div class= "menu-card-white">
          <p><%= link_to "MY MESSAGES", '#' %></p> <%# something /messages %>
        </div>
        <div class= "menu-card-grey">
          <p><%= link_to "MY PROFILE", '#' %></p> <%# something /username %>
        </div>
      </div>
  </div>
</div>

app/views/pages/homepage.html.erb
<div id="homepage">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1494177310973-4841f7d5a882?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80);">
    <%# <%= image_tag "homepage/banner_background.png", alt: "Banner", class: "image_banner" %>
    <div class="homepage-navbar d-flex justify-content-between">
      <%= image_tag "sportsmate-white.png", alt: "Sportsmate-white", width: 161 %>
      <%= link_to "Browse", activities_path, class: "nav-link" %>
    </div>
    <h1>LET'S PLAY <strong><span class="pink-text" data-controller="typed-js"></span></strong></h1>
  </div>
  <div class="main-container">
    <div class="d-flex flex-column">
      <div class="d-flex flex-row justify-content-around">
        <div class="homepage-card-content">
          <div class="content_homepage">
            <h2>SPORT SPORT SPORT</h2>
            <p>There's a breathless hush in the Close to-night.
            Ten to make and the match to win. A bumping pitch and a blinding light, An hour to play and the last man in.</p>
            <p>And it's not for the sake of a ribboned coat,
            Or the selfish hope of a season's fame,
            But his Captain's hand on his shoulder smote. 'Play up! play up! and play the game!'' - Henry Newbolt, 'Vitai Lampada'</p>
          </div>
        </div>
        <div class="homepage-card-headline" style="padding-top: 0px">
          <h1>GET THE BALL ROLLING</h1>
        </div>
      </div>
      <div class="d-flex flex-row justify-content-around">
        <div class="homepage-card-headline basket">
        </div>
        <div class="homepage-card-content">
          <div class="content_homepage">
            <h2>FUN FUN FUN</h2>
            <p>When my thoughts are too heavy, My feelings too numb, When my heart is unsteady, And the tears start to come,
            I put on my running shoes. Tonight I can't hide. I pace myself, breathing, Letting go with every stride.</p>
            <p>The melody of my footsteps, The rhythm of my breaths, Have synchronized into nothing; A calm stillness inside my head.
            I'm light as a feather. I let myself fly. The world is a blur, but tonight ... I'm alive. - Innarenko, 'Alive'</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="footer">
  <div class="footer-logo">
    <%= image_tag "sportsmate.png", alt: "Sportsmate-white", width: 161 %>
  </div>
  <div class="footer-team">
    <ul class="no-bullets">
    <li><h2>TEAM BORRO</h2></li>
      <li><p>Anuth Hatharasinghe</p></li>
      <li><p>Chichi Luan</p></li>
      <li><p>Francesca Mo</p></li>
      <li><p>Chloe Chemin</p></li>
    </ul>
  </div>
</div>

</div>

app/views/pages/my_activities.html.erb
<div class="main-container">
  <div id="my_booking" class="flex-item-1" >
    <h1>STAY AHEAD OF THE GAME</h1>
  </div>
  <div class="flex-item-2">
    <div class="card-container">
      <div class="cards col-sm-6 col-lg-5">
          <div style ="text-decoration:none;">
            <p style="margin-top: 20px">
                <% @activities.each do |activity| %>
                  <div class="grey-scale"><img src="https://source.unsplash.com/random/?<%= activity.title %>"
                  width="300"
                  height="200"/>
                  </div>
                 <strong><%= activity.title.capitalize() %>
                </strong>
                <p><%= activity.location %></p>
                <p>$<%= activity.price %>/hr</p>
                <button type="button" class="btn btn-outline-primary"><%= link_to "Manage my bookings",activity_bookings_path(activity) %></button>
                <% end %>
            </p>
          </div>
        </div>


    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>

      </div>
    </div>
  </div>
</div>

app/views/pages/my_bookings.html.erb
<div class="main-container">
  <div id="my_booking" class="flex-item-1" >
    <h1>SOME YOU WIN, SOME YOU WIN</h1>
  </div>
  <div class="flex-item-2">
    <div class="card-container">
      <div class="cards col-sm-6 col-lg-5">
          <div style ="text-decoration:none;">
            <p style="margin-top: 20px">
                <% @bookings.each do |booking| %>
                  <div class="grey-scale"><img src="https://source.unsplash.com/random/?<%= booking.activity.title %>"
                  width="300"
                  height="200"/>
                  </div>
                 <strong><%= booking.activity.title.capitalize() %>
                </strong>
                <p><%= booking.activity.location %></p>
                <p>$<%= booking.activity.price %>/hr</p>
                <% end %>
                <%# <button type="button" class="btn btn-outline-primary"><%= link_to "More Info", activity_booking_path([@booking.activity, @booking]) %>
            </p>
          </div>
        </div>


    <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>

      </div>
    </div>
  </div>
</div>

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path, method: :get, class: 'd-flex') do |f| %>
  <%= f.search_field :description_or_title_i_cont_any,
    placeholder: "Search...",
    class: "search-button form-control m-2 p-2"%>
    <div class="search-button-icon">
  <%= button_tag(class:"input-group-text border-0") do %>
     <i class="fas fa-search"></i>
  <% end %>
  </div>
<% end %>

app/views/search/index.html.erb
<h1 class="text-center m-20" style="margin-bottom: 20px;"><%= pluralize(@activities.count, "Result") %></h1>

<div class="card-container">
  <div class="cards col-sm-6 col-lg-10">
    <% @activities.each do |activity| %>
      <div class="card-product" style="display: flex;flex-direction: column;justify-content: space-evenly;">

        <div><img src="https://source.unsplash.com/random/?<%= activity.title %>"/>
        </div>

        <div style ="text-decoration:none;">
        <p style="margin-top: 20px">
          <strong style="text-transform: uppercase;"><%= activity.title.capitalize() %></strong>
            <br>
            <%= activity.location %>
            <br>
            $<%= activity.price%>/hr
            <br>
            <%= link_to "More info", activity_path(activity), class:"btn btn-outline-primary", style:"margin-top: 15px" %>
            </p>
          </div>

      </div>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class= "container-navbar" style="display: unset">
  <div class="position-sticky sticky-top navbar navbar-expand-sm navbar-light navbar-lewagon " data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
    <div class="container-fluid" style="padding-left:80px;margin-top:20px;padding-right:80px ">
      <%= link_to activities_path() do %>
        <%= image_tag "sportsmate.png", alt: "Sportsmate", width: 150 %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <form class="d-flex" id="activity_search" action="/search" accept-charset="UTF-8" method="get" style="padding-right: 20px;">
              <%= render 'search/form' %>
            </form>

            <li class="nav-item active" style="padding-right: 20px;">

            <strong><%= link_to "Dashboard", dashboard_path, class: "nav-link" %></strong>

            </li>

            <li class="nav-item nav-link">

            <p>Hi, <%= current_user.username.capitalize %></p>

            </li>

            <li class="nav-item dropdown">
              <%= image_tag "avatar.png", width: "100px", alt: "current_user.username", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "My profile", "#", class: "dropdown-item" %>
                <%= link_to "Settings", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>